### ISSUE TITLE
VMWare - Can't start with  Could not create SDL2 window: Failed loading libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by marcellodesales** [pinfake/android-emulator-x11#2]
Can't get it to start... 

1. Enabled KVM in the VMWAre Guest, running Ubuntu 16

Docker-Compose
====

```
docker-compose up emulator
Starting androidreactnative_emulator_1
Attaching to androidreactnative_emulator_1
emulator_1     | emulator: WARNING: Increasing RAM size to 1GB
emulator_1     | emulator: warning: opening audio output failed
emulator_1     | 
emulator_1     | ERROR: Could not create SDL2 window: Failed loading libGL.so.1: 
     libGL.so.1: cannot open shared object file: No such file or directory
emulator_1     | 
androidreactnative_emulator_1 exited with code 1
```

Docker Engine 
======

```
mdesales@kauai:~/dev/github/public/pinfake/android-react-native$ 
  docker run -ti --privileged --net=host -e DISPLAY=$DISPLAY 
               -v /tmp/.X11-unix:/tmp/.X11-unix 
               -v /usr/lib:/usr/lib 
              pinfake/android-emulator-x11 

emulator WARNING: Increasing RAM size to 1GB
Creating filesystem with parameters:
    Size: 2147483648
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8192
    Inode size: 256
    Journal blocks: 8192
    Label: 
    Blocks: 524288
    Block groups: 16
    Reserved block group size: 127
Created filesystem with 11/131072 inodes and 17193/524288 blocks
resize2fs 1.42.13 (17-May-2015)
The filesystem is already 524288 (4k) blocks long.  Nothing to do!

Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
emulator: warning: opening audio output failed

ERROR: Could not create SDL2 window: Failed loading libGL.so.1: libGL.so.1: 
      cannot open shared object file: No such file or directory
```

Docker info
=====

```
mdesales@kauai:~/dev/github/public/pinfake/android-react-native$ docker info
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 24
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.937 GiB
Name: kauai
ID: HFB6:MYBM:HEN2:ZCPS:GRNU:YQVS:ND7Q:HGDC:7Z63:6NAO:NYUT:B5KO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by pinfake** [comment]
Are you running vmware on a linux host?

**Comment by pinfake** [comment]
However, I never managed to get this running inside a virtual machine, but you seem to got past the kvm issue, the problem seems to be gl acceleration... so, I can only give you hints based on my experience: 

- Be sure to use the xenial version of the docker image.
- Enable graphics hardware acceleration on the vm.

This thing goes against the concept of what a container should be (run anywhere, deploy anywhere, etc). It tightly binds to your host to take advantange of hardware acceleration, so i would try avoiding virtualization if possible.

**Comment by marcellodesales** [comment]
@pinfake Yeah, I have fixed this adding a couple of other dependencies... 

* Mac OS Host
* Latest VMWare Running Ubuntu 16.04 Guest
* Enabled VTx hypervisor, and only with that, I got the directory `/dev/kvm` created in Ubuntu.

All the changes I did to get it to work are at my repo https://github.com/marcellodesales/android-react-native/pull/1/files. I can send you a PR with it, but it has been working... It does suffer from the symptoms you described where the container does have a tight coupling with the OS running the container... Bummer... 

However, I'm building a team to work on Native and we all need consistency on this... Thanks!

<img width="1440" alt="screen shot 2017-03-16 at 9 18 14 pm" src="https://cloud.githubusercontent.com/assets/131457/24069681/e2b2f476-0b6a-11e7-8f3b-730806e8461e.png">

**Comment by pinfake** [comment]
Uhm, did you try the xenial image first?, I think you thought ubuntu 16 was called "trusty", but ubuntu 14 is called "trusty", ubuntu 16 is called "xenial". I tried my xenial image on a xenial and it worked, however i didn't try it under vmware. But as far as you got past kvm issues, it should have worked.

**Comment by marcellodesales** [comment]
@pinfake That's confirmed... It worked really really fast with `xenial`. Sorry for the confusion.

And yeah, the Host is `Mac Os` and guest is `Xenial` under `vmware`.
